express:
	npm i express cors 
typescript:
	npm i -D @types/express @types/node nodemon typescript
tsc_run:
	npm i -g typescript
convert_typescript2javascript:
	tsc
convert_typescript2javascript_reload:
	tsc -w
run_backend:
	npm start
typeorm:
	npm install typeorm --save
reflect-metadata:
	npm install reflect-metadata --save
node_typings:
	npm install @types/node --save-dev
mysql:
	npm install mysql --save
rabbitmq:
	npm i amqplib
	npm i -D @types/amqplib
	docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.9-management
